#!/usr/bin/env python3

# Use  https://www.regextester.com/
# for regex experiments
# install it with => sudo cp xmod /usr/local/bin/xmod

import sys
import os
import re 

def nn(group, default):
        r = 0
        w = 0
        x = 0
        for chr in group:
                if 'r' in group: r = 4
                if 'w' in group: w = 2
                if 'x' in group: x = 1
                if '=' in group: return default
        return str(r + w + x)

def string(num):
        s = ''
        for chr in num:
                n = int(chr, base=10)
                if n & 4: s += 'r'
                else: s += '-'
                if n & 2: s += 'w'
                else: s += '-'
                if n & 1: s += 'x'
                else: s += '-'
        return s

def terminal_output(file, actual, new):
        print(file)
        print(f'permission changed from {actual} {string(actual)} to {new} {string(new)}')

if len(sys.argv) < 3:
        print('Too few arguments')
        quit()
elif len(sys.argv) > 3:
        print('Too many arguments')
        quit()
wanted_permission = sys.argv[1]
file = sys.argv[2]
old_permission = oct(os.stat(file).st_mode)[-3:]
new_permission = ''
m = re.search(',{0,1}([=rwx]{0,3}),{0,1}([=rwx]{0,3}),{0,1}([=rwx]{0,3})', wanted_permission)
if m != None:
        for group, i in zip(m.groups(), range(3)):
                new_permission += nn(group, old_permission[i])
        os.chmod(file, int(new_permission, base=8))
        terminal_output(file, old_permission, new_permission)
else:
        print('No regex matched')
